


SELECT STUDENTID, S.LASTNAME, S.FIRSTNAME
FROM BSTUDENT S NATURAL JOIN BREGISTRATION R NATURAL JOIN BCRSSECTION CS NATURAL JOIN BCOURSE C
WHERE C.TITLE = 'College Algebra'
ORDER BY S.FIRSTNAME;



SELECT CS.COURSEID, F.FACULTYNAME
FROM BSTUDENT S NATURAL JOIN BREGISTRATION R NATURAL JOIN BCRSSECTION CS NATURAL JOIN BFACULTY F
WHERE S.FIRSTNAME = 'Jose' AND S.LASTNAME = 'Diaz';



SELECT T.TERMDESC, COURSEID, C.TITLE
FROM BCRSSECTION CS NATURAL JOIN BTERM T NATURAL JOIN BCOURSE C
WHERE CS.MAXCOUNT < 35 AND T.STARTDATE >= TO_DATE('2021-01-01', 'yyyy-MM-dd')
  AND T.ENDDATE <= TO_DATE('2021-12-31', 'yyyy-MM-dd');



SELECT C.TITLE, R.STUDENTID, R.STATUS
FROM BCOURSE C NATURAL JOIN BREGISTRATION R NATURAL JOIN BCRSSECTION CS
WHERE R.FINAL_GRADE = 'F' OR R.STATUS = 'W';



SELECT CS.COURSEID, T.TERMDESC, CS.ROOMID, CS.MAXCOUNT
FROM BCRSSECTION CS NATURAL JOIN BTERM T
WHERE T.TERMDESC = 'Winter 2021' OR CS.MAXCOUNT > 25;


SELECT COURSEID, C.TITLE
FROM BCOURSE C NATURAL JOIN BCRSSECTION CS LEFT OUTER JOIN BREGISTRATION R ON CS.CSID = R.CSID
WHERE R.CSID IS NULL;

SELECT DISTINCT COURSEID, C.TITLE
FROM BCOURSE C NATURAL JOIN BREGISTRATION R NATURAL JOIN BCRSSECTION CS
WHERE R.STATUS = 'X';



SELECT STUDENTID, S.LASTNAME, C.TITLE, TERMID
FROM BSTUDENT S NATURAL JOIN BREGISTRATION R NATURAL JOIN BCRSSECTION
    NATURAL JOIN BCOURSE C NATURAL JOIN BTERM T
WHERE C.TITLE LIKE '%English%' AND T.TERMDESC = 'Spring 2021'
ORDER BY TERMID;



SELECT DISTINCT S.STUDENTID, S.LASTNAME
FROM BSTUDENT S NATURAL JOIN BMAJOR M
WHERE M.MAJORDESC = 'Data Analytics';



SELECT DISTINCT FACULTYID, F.FACULTYNAME, C.TITLE
FROM BMAJOR M NATURAL JOIN BSTUDENT S NATURAL JOIN BREGISTRATION R
    NATURAL JOIN BCRSSECTION CS NATURAL JOIN BFACULTY F NATURAL JOIN  BCOURSE C
WHERE M.MAJORDESC = 'Computer Science';



SELECT S.STUDENTID, S.FIRSTNAME, S.BIRTHDATE, M.MAJORDESC, CS.CSID, F.FACULTYID
FROM BMAJOR M FULL OUTER JOIN BSTUDENT S ON M.MAJORID = S.MAJORID
    FULL OUTER JOIN BREGISTRATION R ON S.STUDENTID = R.STUDENTID
    FULL OUTER JOIN BCRSSECTION CS ON R.CSID = CS.CSID
    FULL OUTER JOIN BFACULTY F ON CS.FACULTYID = F.FACULTYID
WHERE M.MAJORDESC = 'Accounting' OR F.FACULTYNAME ='Sen'
   OR S.BIRTHDATE BETWEEN TO_DATE('1999-01-01', 'yyyy-MM-dd') AND TO_DATE('1999-12-31', 'yyyy-MM-dd');