SELECT LASTNAME, FIRSTNAME, STATE
FROM CUSTOMERS
WHERE STATE = 'NJ';

SELECT ORDER#, SHIPDATE
FROM ORDERS
WHERE SHIPDATE > '01-APR-09';

SELECT TITLE, CATEGORY
FROM BOOKS
WHERE CATEGORY != 'FITNESS';

SELECT CUSTOMER#, LASTNAME, STATE
FROM CUSTOMERS
WHERE STATE = 'NJ'
   OR STATE = 'GA'
ORDER BY LASTNAME ASC;

SELECT CUSTOMER#, LASTNAME, STATE
FROM CUSTOMERS
WHERE STATE IN ('NJ', 'GA')
ORDER BY LASTNAME ASC;

SELECT ORDER#, ORDERDATE
FROM ORDERS
WHERE ORDERDATE <= '01-APR-09';

SELECT ORDER#, ORDERDATE
FROM ORDERS
WHERE ORDERDATE < '01-APR-09'
   OR ORDERDATE = '01-APR-09';

SELECT LNAME, FNAME
FROM AUTHOR
WHERE LNAME LIKE '%IN%'
ORDER BY LNAME, FNAME;

SELECT LASTNAME, REFERRED
FROM CUSTOMERS
WHERE REFERRED IS NOT NULL;

SELECT TITLE, CATEGORY
FROM BOOKS
WHERE CATEGORY LIKE 'CHILDREN'
   OR CATEGORY LIKE 'COOKING';

SELECT TITLE, CATEGORY
FROM BOOKS
WHERE CATEGORY = 'CHILDREN'
   OR CATEGORY = 'COOKING';

SELECT TITLE, CATEGORY
FROM BOOKS
WHERE CATEGORY IN ('CHILDREN', 'COOKING');

SELECT ISBN, TITLE
FROM BOOKS
WHERE TITLE LIKE '_A_N%'
ORDER BY TITLE DESC;

SELECT TITLE
FROM (SELECT TITLE, (RETAIL - DISCOUNT - COST) AS PROFIT FROM BOOKS)
WHERE PROFIT >= 10
ORDER BY PROFIT DESC;

SELECT TITLE, PROFIT
FROM (SELECT TITLE, (RETAIL - DISCOUNT - COST) AS PROFIT FROM BOOKS)
WHERE PROFIT >= 10
ORDER BY PROFIT DESC;

SELECT *
FROM BOOKS
WHERE (CATEGORY = 'COMPUTER' OR CATEGORY = 'FAMILY LIFE')
  AND (PUBID = 1 OR PUBID = 3)
  AND RETAIL >= 45;

SELECT title, pubdate, category
from books
where category = 'COMPUTER'
  AND pubdate BETWEEN '01-JAN-05' AND '31-DEC-05';

SELECT title, pubdate, category
from books
where category = 'COMPUTER'
  AND pubdate >= '01-JAN-05'
  AND pubdate <= '31-DEC-05';

SELECT title, pubdate, category
from books
where category = 'COMPUTER'
  AND pubdate LIKE '%05';