SELECT title, name
FROM books, publisher
WHERE books.pubid = publisher.pubid;

SELECT C.LASTNAME, C.FIRSTNAME, B.TITLE
FROM CUSTOMERS C, ORDERS O, ORDERITEMS OI, BOOKS B
WHERE C.CUSTOMER# = O.CUSTOMER#
AND O.ORDER# = OI.ORDER#
AND OI.ISBN = B.ISBN
ORDER BY LASTNAME, FIRSTNAME;

SELECT B.title,p.name "Publisher Name"
FROM books B,publisher P
WHERE B.pubid=P.pubid
AND p.name='PRINTING IS US';

SELECT title,pubid,name
FROM books JOIN publisher USING(pubid)
WHERE name='PRINTING IS US';

-- SELECT B.title,B.pubid,P.name
-- FROM books B JOIN publisher2 P
-- ON B.pubid= p.id
-- WHERE name='PRINTING IS US';

SELECT R.FIRSTNAME, R.LASTNAME, C.LASTNAME "Referred"
FROM CUSTOMERS C, CUSTOMERS R
WHERE C.REFERRED = R.CUSTOMER#;








SELECT B.TITLE, P.NAME, P.PHONE
FROM BOOKS B, PUBLISHER P
WHERE B.PUBID = P.PUBID;

SELECT B.TITLE, P.NAME, P.PHONE
FROM BOOKS B NATURAL JOIN PUBLISHER P;



SELECT C.FIRSTNAME, C.LASTNAME, O.ORDER#
FROM CUSTOMERS C, ORDERS O
WHERE O.SHIPDATE IS NULL AND C.CUSTOMER# = O.CUSTOMER#
ORDER BY O.ORDERDATE;

SELECT C.FIRSTNAME, C.LASTNAME, O.ORDER#
FROM CUSTOMERS C NATURAL JOIN ORDERS O
WHERE O.SHIPDATE IS NULL
ORDER BY O.ORDERDATE;



SELECT DISTINCT C.FIRSTNAME, C.LASTNAME, C.CUSTOMER#
FROM CUSTOMERS C, ORDERS O, ORDERITEMS OI, BOOKS B
WHERE C.STATE = 'FL'
  AND C.CUSTOMER# = O.CUSTOMER#
  AND O.ORDER# = OI.ORDER#
  AND OI.ISBN = B.ISBN
  AND B.CATEGORY = 'COMPUTER';

SELECT DISTINCT C.FIRSTNAME, C.LASTNAME, CUSTOMER#
FROM CUSTOMERS C NATURAL JOIN ORDERS O
    NATURAL JOIN ORDERITEMS OI NATURAL JOIN BOOKS B
WHERE C.STATE = 'FL' AND B.CATEGORY = 'COMPUTER';



SELECT DISTINCT B.ISBN, B.TITLE
FROM CUSTOMERS C, ORDERS O, ORDERITEMS OI, BOOKS B
WHERE C.FIRSTNAME = 'JAKE'
  AND C.LASTNAME = 'LUCAS'
  AND C.CUSTOMER# = O.CUSTOMER#
  AND O.ORDER# = OI.ORDER#
  AND OI.ISBN = B.ISBN;

SELECT DISTINCT ISBN, B.TITLE
FROM CUSTOMERS C NATURAL JOIN ORDERS O
    NATURAL JOIN ORDERITEMS OI NATURAL JOIN BOOKS B
WHERE C.FIRSTNAME = 'JAKE'
  AND C.LASTNAME = 'LUCAS';



SELECT B.ISBN, B.TITLE, (OI.PAIDEACH - B.COST) "PROFIT"
FROM CUSTOMERS C, ORDERS O, ORDERITEMS OI, BOOKS B
WHERE C.FIRSTNAME = 'JAKE'
  AND C.LASTNAME = 'LUCAS'
  AND C.CUSTOMER# = O.CUSTOMER#
  AND O.ORDER# = OI.ORDER#
  AND OI.ISBN = B.ISBN
ORDER BY O.ORDERDATE, PROFIT DESC;

SELECT ISBN, B.TITLE, (OI.PAIDEACH - B.COST) "PROFIT"
FROM CUSTOMERS C NATURAL JOIN ORDERS O
    NATURAL JOIN ORDERITEMS OI NATURAL JOIN BOOKS B
WHERE C.FIRSTNAME = 'JAKE'
  AND C.LASTNAME = 'LUCAS'
ORDER BY O.ORDERDATE, PROFIT DESC;



SELECT B.ISBN, B.TITLE
FROM BOOKS B, BOOKAUTHOR BA, AUTHOR A
WHERE A.LNAME = 'ADAMS'
  AND B.ISBN = BA.ISBN
  AND BA.AUTHORID = A.AUTHORID;

SELECT ISBN, B.TITLE
FROM BOOKS B NATURAL JOIN BOOKAUTHOR BA NATURAL JOIN AUTHOR A
WHERE A.LNAME = 'ADAMS';



SELECT P.GIFT
FROM BOOKS B, PROMOTION P
WHERE B.TITLE = 'SHORTEST POEMS'
  AND B.RETAIL BETWEEN P.MINRETAIL AND P.MAXRETAIL;

SELECT P.GIFT
FROM BOOKS B JOIN PROMOTION P
    ON B.RETAIL BETWEEN P.MINRETAIL AND P.MAXRETAIL
WHERE B.TITLE = 'SHORTEST POEMS';



SELECT DISTINCT A.FNAME, A.LNAME
FROM CUSTOMERS C, ORDERS O, ORDERITEMS OI, BOOKS B, BOOKAUTHOR BA, AUTHOR A
WHERE C.FIRSTNAME = 'BECCA' AND C.LASTNAME = 'NELSON'
  AND C.CUSTOMER# = O.CUSTOMER# AND O.ORDER# = OI.ORDER#
  AND OI.ISBN = B.ISBN AND B.ISBN = BA.ISBN AND BA.AUTHORID = A.AUTHORID;

SELECT DISTINCT A.FNAME, A.LNAME
FROM CUSTOMERS C NATURAL JOIN ORDERS O NATURAL JOIN ORDERITEMS OI
    NATURAL JOIN BOOKS B NATURAL JOIN BOOKAUTHOR BA NATURAL JOIN AUTHOR A
WHERE C.FIRSTNAME = 'BECCA' AND C.LASTNAME = 'NELSON';


SELECT B.ISBN, B.TITLE, O.ORDER#, C.STATE
FROM BOOKS B, ORDERITEMS OI, ORDERS O, CUSTOMERS C
WHERE B.ISBN = OI.ISBN(+) AND OI.ORDER# = O.ORDER#(+) AND O.CUSTOMER# = C.CUSTOMER#(+);

SELECT B.ISBN, B.TITLE, O.ORDER#, C.STATE
FROM BOOKS B LEFT OUTER JOIN ORDERITEMS OI ON OI.ISBN = B.ISBN
    LEFT OUTER JOIN ORDERS O ON O.ORDER# = OI.ORDER#
    LEFT OUTER JOIN CUSTOMERS C ON C.CUSTOMER# = O.CUSTOMER#;

SELECT ISBN, B.TITLE, ORDER#, C.STATE
FROM BOOKS B LEFT OUTER JOIN ORDERITEMS OI USING (ISBN)
    LEFT OUTER JOIN ORDERS O USING (ORDER#)
    LEFT OUTER JOIN CUSTOMERS C USING (CUSTOMER#);



SELECT E.FNAME "EMPLOYEE'S NAME", E.JOB "JOB TITLE", NULL "MANAGER'S NAME"
FROM EMPLOYEES E
WHERE E.MGR IS NULL
UNION
SELECT E.FNAME "EMPLOYEE'S NAME", E.JOB "JOB TITLE", M.FNAME "MANAGER'S NAME"
FROM EMPLOYEES E, EMPLOYEES M
WHERE E.MGR = M.EMPNO
ORDER BY "MANAGER'S NAME";

SELECT E.FNAME "EMPLOYEE'S NAME", E.JOB "JOB TITLE", NULL "MANAGER'S NAME"
FROM EMPLOYEES E
WHERE E.MGR IS NULL
UNION
SELECT E.FNAME "EMPLOYEE'S NAME", E.JOB "JOB TITLE", M.FNAME "MANAGER'S NAME"
FROM EMPLOYEES E JOIN EMPLOYEES M
ON E.MGR = M.EMPNO
ORDER BY "MANAGER'S NAME";



SELECT B.TITLE "BOOK TITTLE", P.NAME "PUBLISHER'S NAME",
       B.RETAIL - B.COST "PROFIT AMOUNT", PM.GIFT "FREE GIFT DESCRIPTION"
FROM BOOKS B, PUBLISHER P, PROMOTION PM
WHERE B.PUBID = P.PUBID AND B.RETAIL BETWEEN PM.MINRETAIL AND PM.MAXRETAIL;

SELECT B.TITLE "BOOK TITTLE", P.NAME "PUBLISHER'S NAME",
       B.RETAIL - B.COST "PROFIT AMOUNT", PM.GIFT "FREE GIFT DESCRIPTION"
FROM PROMOTION PM, BOOKS B NATURAL JOIN PUBLISHER P
WHERE B.RETAIL BETWEEN PM.MINRETAIL AND PM.MAXRETAIL;



SELECT B.ISBN
FROM BOOKS B
WHERE B.ISBN NOT IN (SELECT OI.ISBN FROM ORDERITEMS OI);

SELECT B.ISBN FROM BOOKS B
MINUS
SELECT OI.ISBN FROM ORDERITEMS OI;