SELECT TITLE, RETAIL
FROM BOOKS
WHERE RETAIL <
      (SELECT AVG(RETAIL) FROM BOOKS);



SELECT TITLE, CATEGORY, COST
FROM BOOKS
         NATURAL JOIN
         (SELECT CATEGORY, AVG(COST) AVERAGECOST FROM BOOKS GROUP BY CATEGORY)
WHERE COST < AVERAGECOST;



SELECT ORDER#
FROM ORDERS
WHERE SHIPSTATE =
      (SELECT SHIPSTATE FROM ORDERS WHERE ORDER# = 1014);



SELECT ORDER#, SUM(QUANTITY * PAIDEACH)
FROM ORDERITEMS
GROUP BY ORDER#
HAVING SUM(QUANTITY * PAIDEACH) >
       (SELECT SUM(QUANTITY * PAIDEACH) FROM ORDERITEMS WHERE ORDER# = 1008);



SELECT FNAME, LNAME
FROM AUTHOR
         NATURAL JOIN BOOKAUTHOR
WHERE ISBN IN
      (SELECT ISBN
       FROM ORDERITEMS
       HAVING SUM(QUANTITY) =
              (SELECT MAX(SUM(QUANTITY)) FROM ORDERITEMS GROUP BY ISBN)
       GROUP BY ISBN);



SELECT TITLE
FROM BOOKS
WHERE CATEGORY IN
      (SELECT DISTINCT CATEGORY
       FROM BOOKS
                NATURAL JOIN ORDERITEMS
                NATURAL JOIN ORDERS
       WHERE CUSTOMER# = 1007)
  AND ISBN NOT IN (SELECT ISBN
                   FROM ORDERITEMS
                            NATURAL JOIN ORDERS
                   WHERE CUSTOMER# = 1007);



SELECT SHIPCITY, SHIPSTATE
FROM ORDERS
WHERE (SHIPDATE - ORDERDATE) =
      (SELECT MAX(SHIPDATE - ORDERDATE) FROM ORDERS);



SELECT DISTINCT CUSTOMER#
FROM ORDERS
         NATURAL JOIN ORDERITEMS
WHERE ISBN IN (SELECT ISBN FROM BOOKS WHERE RETAIL = (SELECT MIN(RETAIL) FROM BOOKS));



SELECT COUNT(DISTINCT CUSTOMER#)
FROM ORDERS
         NATURAL JOIN ORDERITEMS
WHERE ISBN IN (SELECT ISBN
               FROM BOOKAUTHOR
                        NATURAL JOIN AUTHOR
               WHERE FNAME = 'JAMES'
                 AND LNAME = 'AUSTIN');



SELECT TITLE
FROM BOOKS
WHERE PUBID = (SELECT PUBID FROM BOOKS WHERE TITLE = 'THE WOK WAY TO COOK');



SELECT 1.5 * ((SELECT SUM(SHIPCOST) FROM ORDERS) +
              (SELECT SUM(QUANTITY * PAIDEACH) FROM ORDERITEMS)) / 100 AS SURCHAGE
FROM DUAL;

SELECT 4 * SUM(SHIPCOST + COST) / 100
FROM (SELECT ORDER#, NVL(SHIPCOST, 0) SHIPCOST FROM ORDERS)
         NATURAL JOIN
     (SELECT ORDER#, SUM(QUANTITY * PAIDEACH) COST FROM ORDERITEMS GROUP BY ORDER#)
WHERE SHIPCOST + COST >
      (SELECT AVG(SHIPCOST + COST)
       FROM (SELECT ORDER#, NVL(SHIPCOST, 0) SHIPCOST FROM ORDERS)
                NATURAL JOIN
            (SELECT ORDER#, SUM(QUANTITY * PAIDEACH) COST FROM ORDERITEMS GROUP BY ORDER#));