SELECT INITCAP(FIRSTNAME), INITCAP(LASTNAME)
FROM CUSTOMERS;



SELECT CUSTOMER#, NVL2(REFERRED, 'REFERRED', 'NOT REFERRED')
FROM CUSTOMERS;



SELECT B.TITLE, TO_CHAR(OI.QUANTITY * (OI.PAIDEACH - B.COST), '$999.99') PROFIT
FROM ORDERITEMS OI
         NATURAL JOIN BOOKS B
WHERE OI.ORDER# = 1002;



SELECT TITLE, ROUND((RETAIL - COST) / COST * 100, 0) || '%' PERCENTAGEOFMARKUP
FROM BOOKS;



SELECT TO_CHAR(SYSDATE, 'DAY HH24:MI:SS')
FROM DUAL;



SELECT TITLE, LPAD(COST, 12, '*')
FROM BOOKS;



SELECT DISTINCT LENGTH(ISBN)
FROM BOOKS;



SELECT TITLE, PUBDATE, SYSDATE, TRUNC(MONTHS_BETWEEN(SYSDATE, PUBDATE)) AGE
FROM BOOKS;



SELECT NEXT_DAY(SYSDATE, 'WEDNESDAY')
FROM DUAL;



SELECT CUSTOMER#, SUBSTR(ZIP, 3, 1) THIRD, SUBSTR(ZIP, 4, 1) FOURTH, INSTR(CUSTOMER#, 3)
FROM CUSTOMERS;



SELECT TITLE,
       CATEGORY,
       RETAIL                          CURRENTPRICE,
       DECODE(CATEGORY,
              'COMPUTER', ROUND(RETAIL * 1.10, 2),
              'FITNESS', ROUND(RETAIL * 1.15, 2),
              'SELF HELP', ROUND(RETAIL * 1.25, 2),
              ROUND(RETAIL * 1.03, 2)) REVISEDPRICE
FROM BOOKS
ORDER BY CATEGORY, TITLE;